# default config
spring:
  datasource:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://HOSTNAME:PORT/DATABASE?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
      username: USERNAME
      password: PASSWORD
  jpa:
    generate-ddl: true
    show-sql: false
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
  resources:
    static-locations: classpath:/static/
  profiles:
    active:
    - logging-daily
server:
  port: 8080
logging:
  config: classpath:logback-woomin.xml
  level:
    dev:
      hwiveloper:
        naranim:
          mapper: INFO

# additional config
spring.jpa.properties.hibernate.format_sql : true
  
# keys
keys:
  national-assembly-info-service: SERVICE_KEY
  agenda-schedule-info-service: SERVICE_KEY
  common-code-service: SERVICE_KEY
  poll-place-service: SERVICE_KEY
  vote-service: SERVICE_KEY
  winner-service: SERVICE_KEY