name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Set up JDK 1.8
      uses: actions/setup-java@master
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file pom.xml -DDB_HOST=${{secrets.DB_HOST}} -DDB_PORT=${{secrets.DB_PORT}} -DDB_NAME=${{secrets.DB_NAME}} -DDB_USER=${{secrets.DB_USER}} -DDB_PASS=${{secrets.DB_PASS}} -DGOV_API_KEY=${{secrets.GOV_API_KEY}}
    
    - name: copy file via ssh password
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        password: ${{ secrets.SSH_PASS }}
        port: ${{ secrets.SSH_PORT }}
        source: "target/naranim-${{secrets.VERSION}}.war"
        target: "/home/pi/naranim"
        overwrite: true
